# This is a basic workflow to help you get started with Actions
name: build_kernel

# Controls when the action will run.
on:
  # Triggers the workflow on push events but only for the eleven branch
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Build_Kernel
        run:
            sudo chmod a+x build/build_kernel.sh && sudo bash build/build_kernel.sh
        env:
            TELEGRAM_BOT: ${{ secrets.TELEGRAM_BOT }}
            TELEGRAM_GROUP: ${{ secrets.TELEGRAM_GROUP }}

      - name: Prepare artifact
        if: success()
        id: prepareArtifact
        run: |
          ReleaseName=`ls TEMP/*.zip | awk -F '(/|.zip)' '{print $2}'` && echo "ReleaseName=$ReleaseName" >> $GITHUB_OUTPUT
          unzip TEMP/*.zip -d Final

      - uses: actions/upload-artifact@v4
        name: Upload
        with:
          name: ${{ steps.prepareArtifact.outputs.ReleaseName }}
          path: "Final/*"